#ifndef _DEV_LCD_DSBK2348A_H_
#define _DEV_LCD_DSBK2348A_H_

#define CON_LCD_WHEEL_WATER_BOX             0
#define CON_LCD_WHEEL_WATER_LEVEL_LOW_MORE  1
#define CON_LCD_WHEEL_WATER_LEVEL_LOW       2
#define CON_LCD_WHEEL_WATER_LEVEL_MIDDLE    3
#define CON_LCD_WHEEL_WATER_LEVEL_HIGH      4
#define CON_LCD_WHEEL_WATER_LEVEL_HIGH_MORE 5
#define CON_LCD_TANK_WATER_LEVEL_LOW_MORE  6
#define CON_LCD_TANK_WATER_LEVEL_LOW       7
#define CON_LCD_TANK_WATER_LEVEL_MIDDLE    8
#define CON_LCD_TANK_WATER_LEVEL_HIGH      9
#define CON_LCD_TANK_WATER_LEVEL_HIGH_MORE 10
#define CON_LCD_CONNECT_STT                11
#define CON_LCD_RF_STT                     12
#define CON_LCD_PUMP_WATER_STT             13//抽水


#define CON_LCD_DEPUMP_MOTOR_STT             14//抽水电机
#define CON_LCD_DEPUMP_MOTOR_FAN1_STT         15//抽水电机扇叶
#define CON_LCD_DEPUMP_MOTOR_FAN2_STT         16//抽水电机扇叶

#define CON_LCD_DEPUMP_WATER_ARROWS1_STT      (CON_LCD_DEPUMP_MOTOR_FAN2_STT+1)//抽水箭头       17
#define CON_LCD_DEPUMP_WATER_ARROWS2_STT      (CON_LCD_DEPUMP_MOTOR_FAN2_STT+2)//抽水箭头       18
#define CON_LCD_DEPUMP_WATER_ARROWS3_STT      (CON_LCD_DEPUMP_MOTOR_FAN2_STT+3)//抽水箭头
#define CON_LCD_DEPUMP_WATER_ARROWS4_STT      (CON_LCD_DEPUMP_MOTOR_FAN2_STT+4)//抽水箭头
#define CON_LCD_DEPUMP_WATER_ARROWS5_STT      (CON_LCD_DEPUMP_MOTOR_FAN2_STT+5)//抽水箭头
#define CON_LCD_DEPUMP_WATER_ARROWS6_STT      (CON_LCD_DEPUMP_MOTOR_FAN2_STT+6)//抽水箭头

#define CON_LCD_PUMP_MOTOR_STT              (CON_LCD_DEPUMP_WATER_ARROWS6_STT+1)//加水
#define CON_LCD_PUMP_MOTOR_FAN1_STT         (CON_LCD_PUMP_MOTOR_STT+1)//加水电机扇叶
#define CON_LCD_PUMP_MOTOR_FAN2_STT         (CON_LCD_PUMP_MOTOR_STT+2)//加水电机扇叶
#define CON_LCD_PUMP_WATER_ARROWS1_STT      (CON_LCD_PUMP_MOTOR_FAN2_STT+1)//抽水箭头
#define CON_LCD_PUMP_WATER_ARROWS2_STT      (CON_LCD_PUMP_MOTOR_FAN2_STT+2)//抽水箭头
#define CON_LCD_PUMP_WATER_ARROWS3_STT      (CON_LCD_PUMP_MOTOR_FAN2_STT+3)//抽水箭头
#define CON_LCD_PUMP_WATER_ARROWS4_STT      (CON_LCD_PUMP_MOTOR_FAN2_STT+4)//抽水箭头
#define CON_LCD_PUMP_WATER_ARROWS5_STT      (CON_LCD_PUMP_MOTOR_FAN2_STT+5)//抽水箭头
#define CON_LCD_PUMP_WATER_ARROWS6_STT      (CON_LCD_PUMP_MOTOR_FAN2_STT+6)//抽水箭头

#define CON_LCD_MANUAL_STT                  (CON_LCD_PUMP_WATER_ARROWS6_STT+1)//自动 32
#define CON_LCD_AUTO_STT                    (CON_LCD_PUMP_WATER_ARROWS6_STT+2)//手动        33

#define CON_LCD_WHEEL_WATER_LOW_STT             (CON_LCD_AUTO_STT+1)//水车缺水        34
#define CON_LCD_WHEEL_WATER_HIGH_MORE_STT       (CON_LCD_WHEEL_WATER_LOW_STT+1)//水车满水  35

#define CON_LCD_CHANGE_WATER_STT             (CON_LCD_WHEEL_WATER_HIGH_MORE_STT+1)//换水 36

#define CON_LCD_TANK_WATER_HIGH_MORE_STT        (CON_LCD_CHANGE_WATER_STT+1)//水箱缺水 37
#define CON_LCD_TANK_WATER_LOW_STT              (CON_LCD_CHANGE_WATER_STT+2)//水箱满水  38

#define CON_LCD_TEST1   (CON_LCD_TANK_WATER_HIGH_MORE_STT + 1)
#define CON_LCD_TEST2   (CON_LCD_TANK_WATER_HIGH_MORE_STT + 2)
#define CON_LCD_TEST3   (CON_LCD_TANK_WATER_HIGH_MORE_STT + 3)
#define CON_LCD_TEST4   (CON_LCD_TANK_WATER_HIGH_MORE_STT + 4)
#define CON_LCD_TEST5   (CON_LCD_TANK_WATER_HIGH_MORE_STT + 5)
#define CON_LCD_TEST6   (CON_LCD_TANK_WATER_HIGH_MORE_STT + 6)
#define CON_LCD_TEST7   (CON_LCD_TANK_WATER_HIGH_MORE_STT + 7)
#define CON_LCD_TEST8   (CON_LCD_TANK_WATER_HIGH_MORE_STT + 8)

#define CON_WATER_CTRL_AUTO 0
#define CON_WATER_CTRL_MANUAL 1

#define CON_WATER_CTRL_ON 1
#define CON_WATER_CTRL_OFF 0
#define CON_WATER_CTRL_IDEL 2   //息屏运行


void SYS_LCD_Init(void);
uint8_t SYS_LCD_Set_Stt(uint8_t flag);
uint8_t SYS_LCD_Set_Time(TIME tm, uint8_t bcd);
uint8_t SYS_LCD_Set_Head(uint8_t flag);
uint8_t SYS_LCD_Set_Tank_Stt(uint8_t flag);
uint8_t SYS_LCD_Set(uint8_t index, uint8_t data);
uint8_t SYS_LCD_Set_Wheel_Water_Level(uint8_t flag, uint8_t count);
uint8_t SYS_LCD_Set_Tank_Water_Level(uint8_t flag, uint8_t count);
uint8_t SYS_LCD_Onoff(uint8_t onoff);
uint8_t SYS_LCD_Get_Onoff(void);
uint8_t SYS_LCD_Clr_Year_High();
void SYS_LCD_Handld(void);

#endif
